tictactaco/config/routes.rb
Rails.application.routes.draw do
  root 'games#index'

  get 'games/:id' => 'games#show', as: :game
  post 'games' => 'games#create'
  post "/games/:id/:position" => 'games#play', as: :play_game

end

tictactaco/app/models/game.rb
class Game < ActiveRecord::Base



  def computer_play

    # get open squares
    open_squares = (1..9).to_a.select do |i|
      tile(i).blank?
    end
    # choose a random square from the open
    rando_square = open_squares.sample
    # mark as O
    place(rando_square, "O")

  end

  def winner

    ["X", "O"].each do |player|

      winning_combos = [
        [7,8,9],
        [1,2,3],
        [4,5,6],
        [1,4,7],
        [2,5,8],
        [3,6,9],
        [1,5,9],
        [3,5,7]
      ]

      winning_combos.each do |combo|
        return player if all_tiles(combo, player)
      end


    end

    return ""


  end

  def tile(number)
    # sort of calls position_5 for 5
    self["position_#{number}"]
  end

  def all_tiles(tiles, player)
    values = tiles.map{|i| tile(i)}
    values.all? {|i| i == player }
  end

  def place(position, player)
    self["position_#{position}"] = player
  end
end

tictactaco/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

tictactaco/app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
    @game = Game.new
  end

  def create
    @game = Game.new
    if @game.save
      redirect_to game_path(id: @game.id)
    else
      render :new
    end
  end

  def show
    @game = Game.find params[:id]
  end

  def play
    @game = Game.find params[:id]

    if @game.tile(params[:position].to_i).present?
      render :sneaky
      return
    end
    
    @game.place(params[:position].to_i, "X")
    @game.computer_play
    @game.save
  end
end

tictactaco/app/helpers/application_helper.rb
module ApplicationHelper
end

tictactaco/app/helpers/games_helper.rb
module GamesHelper
end

tictactaco/app/views/games/_game.html.erb
<% if @game.winner.present? %>
  <%= @game.winner %> WINS
<% end %>

<div class="game">
  <% (1..9).to_a.each do |i| %>
    <%= link_to play_game_path(id: @game.id, position: i), method: :post, class: "playit", remote: true do %>
      <div id="position_<%=i %>" class="tile">
        <%= @game.tile i %>
      </div>
    <% end %>
  <% end %>
</div>

tictactaco/app/views/games/index.html.erb
<h1>Games#index</h1>
<p>Find me in app/views/games/index.html.erb</p>

<%= form_for @game do |f| %>
  <%= f.submit  "Start Game" %>
<% end %>

tictactaco/app/views/games/play.js.erb
setTimeout(function(){
  $("#game_board").html("<%= j render partial: "game" %>");

  $("a.playit").on("click", function(){
    // mark X instantly
    $(this).find(".tile").text("X");
  })
}, 1500);

tictactaco/app/views/games/show.html.erb
<h1>Games#show</h1>

<div id="game_board">
  <%= render partial: "game" %>
</div>

tictactaco/app/views/games/sneaky.js.erb
alert("You are turrble");

$("#game_board").html("<%= j render partial: "game" %>");

$("a.playit").on("click", function(){
  // mark X instantly
  $(this).find(".tile").text("X");
})

tictactaco/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tictactaco</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>