tweetie/config/routes.rb
Rails.application.routes.draw do
  root 'tweets#index'

  get 'compose' => 'tweets#new', as: :new_tweet
  post 'compost' => 'tweets#create', as: :tweets

end

tweetie/app/models/tweet.rb
class Tweet < ActiveRecord::Base
end

tweetie/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
  end

  def new
    @tweet = Tweet.new
  end
end

tweetie/app/helpers/tweets_helper.rb
module TweetsHelper
end

tweetie/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tweetie</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

tweetie/app/views/tweets/index.html.erb
<h1>Tweets#index</h1>

<div class="well">
  <div class="text-right">
    <%= link_to 'New Tweet', new_tweet_path, class: "btn btn-primary" %>
  </div>
</div>

<script>

  $(window).ready(function(){
    $.getJSON("/movies.json").then(function(data){
      var movies = data.movies;
      console.log(movies);
      // use underscore on the data
    })
  });

</script>

tweetie/app/views/tweets/new.html.erb
<h1>Tweets#new</h1>
<%= simple_form_for @tweet do |f| %>

  <div class="row">
    <div class="col-xs-12">
      <%= f.input :body, label: false, as: :text, placeholder: "What's Happening?" %>
    </div>
  </div>

  <div class="row form-group">
    <div class="col-xs-10">
      <div class="text-right">
        <div id="counter"></div>
      </div>
    </div>
    <div class="col-xs-2">
      <%= f.submit class: "btn btn-lg btn-success" %>
    </div>

  </div>






<% end %>